# Use the official Golang image as a parent image
FROM golang:1.21

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the dependencies - they will be cached if the go.mod and go.sum files don't change
RUN go mod download

# Copy the rest of your project files
COPY . .

# Command to run the test binary; adjust if your test binary has a different name
CMD ["go", "test", "-tags=e2e", "./..."]
